ALTER PROCEDURE [dbo].[SP_WRITE_VENTAS]
@OP tinyint = 0,
@TMP_ID_CLIENTE TINYINT = 0,
@TMP_ID_ALMACEN TINYINT = 0,
@TMP_FOLIO TINYINT = 0,
@TMP_SERIE CHAR(3) = '',
@TMP_ID_TIPODOCTO TINYINT = 0,
@TMP_ID_PRODUCTO INT = 0,
@TMP_CANTIDAD FLOAT = 0,
@TMP_IMPORTE FLOAT = 0,
@TMP_IVA FLOAT = 0,
@TMP_FECHA DATETIME = '01/01/1900',
@TMP_MONTO FLOAT = 0
AS
BEGIN 
	if @OP = 1
	BEGIN
    
		INSERT INTO dbo.TMPVENTA_DETALLE (TMP_ID_CLIENTE,TMP_ID_ALMACEN,TMP_FOLIO,TMP_SERIE,TMP_ID_TIPODOCTO,TMP_ID_PRODUCTO,TMP_CANTIDAD,TMP_IMPORTE,TMP_IVA, TMP_FECHA, TMP_MONTO)			
		VALUES(@TMP_ID_CLIENTE,@TMP_ID_ALMACEN,@TMP_FOLIO,@TMP_SERIE,@TMP_ID_TIPODOCTO,@TMP_ID_PRODUCTO,@TMP_CANTIDAD,@TMP_IMPORTE,@TMP_IVA,@TMP_FECHA,@TMP_MONTO)

		  
	END
	
	ELSE IF @OP = 2
		BEGIN
			DELETE FROM TMPVENTA_DETALLE WHERE TMP_FOLIO = @TMP_FOLIO and TMP_SERIE = @TMP_SERIE
		END

	ELSE IF @OP = 3
		BEGIN
			INSERT INTO VENTAS (VE_FOLIO, VE_SERIE, VE_ID_TIPODOCTO, VE_MONTO, VE_ID_CLIENTE, VE_ID_ALMACEN, VE_FECHA)
			SELECT TMP_FOLIO, TMP_SERIE, TMP_ID_TIPODOCTO, TMP_MONTO, TMP_ID_CLIENTE, TMP_ID_ALMACEN, TMP_FECHA
			FROM TMPVENTA_DETALLE

			INSERT INTO VENTAS_DETALLE (VD_FOLIO, VD_SERIE, VD_ID_TIPODOCTO, VD_ID_PRODUCTO, VD_CANTIDAD, VD_IMPORTE, VD_IVA)
			SELECT TMP_FOLIO, TMP_SERIE, TMP_ID_TIPODOCTO, TMP_ID_PRODUCTO, TMP_CANTIDAD, TMP_IMPORTE, TMP_IVA
			FROM TMPVENTA_DETALLE
			

			DELETE from dbo.TMPVENTA_DETALLE

		END

END

SELECT * FROM dbo.VENTAS
